# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5db5d8beff6774dfa9d650a22adf07b8"
name = "colabah-style-dna"
application_url = "https://colabah-style-dna.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://colabah-style-dna.onrender.com/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "write_customers,read_customers"

[build]
automatically_update_urls_on_dev = false

[app_proxy]
url = "https://colabah-style-dna.onrender.com/apps/proxy"
subpath = "style-dna-proxy"
prefix = "apps"